### ISSUE TITLE
Service Error

### ISSUE THREAD

**Issue by NotOneRing** [graphistry/graphistry-js#15]
Dear Contributor,
Sorry for the inconvenience I might cause.
I got errors over and over again to note that "Service error
Error 1: Try logging out and back in, or check file format & logs" when I upload graph file in ".json" format.

Could you please kindly help me through this difficulty?
Thanks so much for your precious time and great efforts!!!

![image](https://user-images.githubusercontent.com/86668994/124776530-1a926680-df72-11eb-978e-2af32322cc4c.png)

**Comment by lmeyerov** [comment]
This should be fixed (awhile back)
