### ISSUE TITLE
If graphistry-js is based on WebGPU?

### ISSUE THREAD

**Issue by zhaonaiy** [graphistry/graphistry-js#166]
Hello,
      I was wondering what technology used, WebGL or WebGPU, used in graphistry-js?  Thanks.

**Comment by lmeyerov** [comment]
Our backend is opencl/CUDA, and frontend webgl ~1.0

We estimate webgl2/webgpu/etc would only give 10-20% perf improvement as we already work on large buffers

We are targeting improving the frontend scale by 10-100x this year, but via deeper optimizations than switching languages
